#!/bin/bash
./build-test-mh

fail() {
  echo -e "\033[1;31m failed\033[0;0m"
  exit 1
}

ok() {
  echo -e "\033[1;32m ok\033[0;0m"
}

for file in *; do
  if [[ -x $file ]] && head -n1 $file | grep -q '^#!.*test-mh'; then
    echo -n running $file && ./$file >& /dev/null && ok || fail $file
  fi
done
