caterwaul.module( 'mulholland.mh' ,function($) { (function( ) {var contains_short=function(argv,o) {;
return(function( ) {var pattern=new RegExp( ( '^-(?!-)\\w*' + (o) + '' ) ) ;
return( (function(xs) {var x,x0,xi,xl,xr;
for(var x=xs[0] ,xi=0,xl=xs.length,x1;
xi<xl;
 ++xi) {x=xs[xi] ;
if(x1= ( (pattern) .exec(x) ) )return x1}return false} ) .call(this,argv) ) } ) .call(this) } ,read_file=function(f) {;
return require( 'fs' ) .readFileSync(f, 'utf8' ) } ,output=function(t) {;
return process.stdout.write(t.as_caterwaul() .toString() + ';\n' , 'utf8' ) } ;
return($.mulholland.mh_main=function(argv) {;
return!argv.length||contains_short(argv, 'i' ) ?$.mulholland.mh_repl(argv) : (function( ) {var mh=$.mulholland.mh() ;
return( (function(xs) {var x,x0,xi,xl,xr;
for(var xi=0,xl=xs.length;
xi<xl;
 ++xi)x=xs[xi] , ( (output) .call( {x0:x0,xi:xi,xl:xl,xs:xs,xr:xr} ,x) ) ;
return xs} ) .call(this, (function(xs) {var x,x0,xi,xl,xr;
for(var xr=new xs.constructor() ,xi=0,xl=xs.length;
xi<xl;
 ++xi)x=xs[xi] ,xr.push( ( (mh) .call( {x0:x0,xi:xi,xl:xl,xs:xs,xr:xr} ,x) ) ) ;
return xr} ) .call(this, (function(xs) {var x,x0,xi,xl,xr;
for(var xr=new xs.constructor() ,xi=0,xl=xs.length;
xi<xl;
 ++xi)x=xs[xi] ,xr.push( ( (read_file) .call( {x0:x0,xi:xi,xl:xl,xs:xs,xr:xr} ,x) ) ) ;
return xr} ) .call(this,argv) ) ) ) } ) .call(this) } ,$.mulholland.mh_repl=function(argv) {;
return(function( ) {var mh=$.mulholland.mh() ,evaluator=function(s,_1,_2,cc) {;
return(function( ) {try{return(cc(null,mh(s) .structure() ) ) }catch(e) {return(cc(e,undefined) ) } } ) .call(this) } ;
return( (function(it) {return(require( 'repl' ) .start( 'mh> ' ,undefined,evaluator) ) ,it} ) .call(this, ( (function(xs) {var x,x0,xi,xl,xr;
for(var xi=0,xl=xs.length;
xi<xl;
 ++xi)x=xs[xi] , ( (mh) .call( {x0:x0,xi:xi,xl:xl,xs:xs,xr:xr} ,x) ) ;
return xs} ) .call(this, (function(xs) {var x,x0,xi,xl,xr;
for(var xr=new xs.constructor() ,xi=0,xl=xs.length;
xi<xl;
 ++xi)x=xs[xi] ,xr.push( ( (read_file) .call( {x0:x0,xi:xi,xl:xl,xs:xs,xr:xr} ,x) ) ) ;
return xr} ) .call(this, (function(xs) {var x,x0,xi,xl,xr;
for(var xr=new xs.constructor() ,xi=0,xl=xs.length,x0;
xi<xl;
 ++xi)x=xs[xi] , ( /^-/ .test(x) ) ||xr.push(x) ;
return xr} ) .call(this,argv) ) ) ) ) ) } ) .call(this) } ,$.mulholland.mh=function() {;
return(function( ) {var parse=$.mulholland() ,define=function(match) {;
return match&& (function(it) {return(blank) } ) .call(this, ( (toplevel_rewriter= (toplevel_rewriter) .extend( [ [match._x,toplevel_rewriter(match._y) ] ] ) ) ) ) } ,blank=parse( '_' ) ,rewrite=function(match) {;
return match&&toplevel_rewriter.extend( (function(xs) {var x,x0,xi,xl,xr;
for(var xi=0,xl=xs.length;
xi<xl;
 ++xi)x=xs[xi] , ( (assert_valid_rewrite) .call( {x0:x0,xi:xi,xl:xl,xs:xs,xr:xr} ,x) ) ;
return xs} ) .call(this,toplevel_rewriter(match._y) .flatten_all( ',' ) ) ) (match._x) } ,compile=function(match) {;
return match&& (function( ) {var f=$.compile( (toplevel_rewriter(match._x) ) .as_caterwaul(parse) ) ;
return( (function(it) {return(it.replace=function(m) {;
return f(m) } ) ,it} ) .call(this, (match._x) ) ) } ) .call(this) } ,assert_valid_rewrite=function(tree) {;
return tree.resolved_data() === '=' || (function( ) {throw new Error( ( '/@: ' + (tree.structure() ) + ' is not a valid rewrite rule' ) ) } ) .call(this) } ,toplevel_rewriter=$.mulholland.rewriter( [ [parse( '_x /@ _y' ) ,rewrite] , [parse( '_x =@ _y' ) ,define] , [parse( '@js! _x' ) ,compile] ] ) ;
return($.merge(function(_) {return(function(it) {return(it.pop() ) } ) .call(this, ( (function(xs) {var x,x0,xi,xl,xr;
for(var xr=new xs.constructor() ,xi=0,xl=xs.length;
xi<xl;
 ++xi)x=xs[xi] ,xr.push( ( (toplevel_rewriter) .call( {x0:x0,xi:xi,xl:xl,xs:xs,xr:xr} ,x) ) ) ;
return xr} ) .call(this,parse(_) .flatten_all( ';' ) ) ) ) } , {define:define,rewrite:rewrite,compile:compile,parse:parse,js:js,output:output} ) ) } ) .call(this) } ) } ) .call(this) } ) ;
