caterwaul.module( 'mulholland.rewrite' ,function($) {$.mulholland.rewriter=function(rules) {;
return(function( ) {var current=Array.prototype.slice.call( (rules) ) ,change=null,pattern_complexity=function() {;
return(function(xs) {var x,x0,xi,xl,xr;
for(var x0= (0x10000000) ,xi=0,xl=xs.length;
xi<xl;
 ++xi)x=xs[xi] ,x0= (Math.min(x0,x[0] .complexity() ) ) ;
return x0} ) .call(this,current) } ,rewrite_once=function(t) {;
return(function(it) {return(change=change||it) ,it} ) .call(this, ( (function(xs) {var x,x0,xi,xl,xr;
for(var xl=xs.length,xi=xl-1,x=xs[xi] ,x1;
xi>=0;
 --xi) {x=xs[xi] ;
if(x1= ( (x[1] ) .replace(x[0] .match(t) ) ) )return x1}return false} ) .call(this,current) ) ) } ,deep_rewriter=function() {var c=pattern_complexity() ;
return function(t) {;
return t.complexity() >=c? (t) .rmap(rewrite_once) :t} } ,fixed_point=function() {var r=deep_rewriter() ;
var result=function(t) {;
return(change=null, (function(it) {return(change?fix(it) :it) } ) .call(this, (r(t) ) ) ) } ;
var fix=result;
return result} ,transitive_limit=function(r) {;
return[r[0] ,fixed_point() (r[1] ) ] } ,uniq=function(rs) {;
return(function(xs1) {var x2,x01,xi1,xl1,xr1;
for(var xr1=new xs1.constructor() ,xi1=0,xl1=xs1.length;
xi1<xl1;
 ++xi1)x2=xs1[xi1] , ( ~r[rs| [xi>ri&& (x[0] ) .match(r[0] ) ] ] (x2) ) ||xr1.push(x2) ;
return xr1} ) .call(this,rs) } ,current=uniq( (current) .concat( ( (function(xs1) {var x2,x01,xi1,xl1,xr1;
for(var xr1=new xs1.constructor() ,xi1=0,xl1=xs1.length;
xi1<xl1;
 ++xi1)x2=xs1[xi1] ,xr1.push( (transitive_limit(x2) ) ) ;
return xr1} ) .call(this,current) ) ) ) ,rewrite=fixed_point() ;
return($.merge(rewrite, {rules:current,extend:function(rs) {;
return $.mulholland.rewriter( (current) .concat( (rs) ) ) } } ) ) } ) .call(this) } } ) ;
