caterwaul.module( 'mulholland.rewrite' ,function($) {$.mulholland.rewriter=function(rules) {;
return(function( ) {var current_list=Array.prototype.slice.call( (rules) ) ,rewrite_once=function(t) {;
return(function(xs) {var x,x0,xi,xl,xr;
for(var xl=xs.length,xi=xl-1,x=xs[xi] ,x_3_itU5DovY6hdPPnZfYcQN7g;
xi>=0;
 --xi) {x=xs[xi] ;
if(x_3_itU5DovY6hdPPnZfYcQN7g= (x[1] .constructor===Function?x[1] .call(rewrite, (x[0] ) .match(t) ) : (x[1] ) .replace(x[0] .match(t) ) ) )return x_3_itU5DovY6hdPPnZfYcQN7g}return false} ) .call(this,current_list) } ,fixed_point=function(t) {;
return(function( ) {var r=null;
return( (function(it) {return(r) } ) .call(this, ( (function(xs) {var x,x0,xi,xl,xr;
for(var x=xs,xi=0,x0,xl;
x0= (x) ;
 ++xi)x= (r=rewrite_once(x) ||r) ;
return x} ) .call(this,t) ) ) ) } ) .call(this) } ,transitive_limit=function(r) {;
return r[1] .constructor===Function?r: [r[0] ,fixed_point(r[1] ) ] } ,uniq=function(rs) {;
return(function(rs) {var r,r0,ri,rl,rr;
for(var rr=new rs.constructor() ,ri=0,rl=rs.length,r0;
ri<rl;
 ++ri)r=rs[ri] , ( (function(xs) {var x,x0,xi,xl,xr;
for(var x=xs[0] ,xi=0,xl=xs.length,x_3_itU5DovY6hdPPnZfYcQN7g;
xi<xl;
 ++xi) {x=xs[xi] ;
if(x_3_itU5DovY6hdPPnZfYcQN7g= (xi>ri&& (x[0] ) .match(r[0] ) ) )return x_3_itU5DovY6hdPPnZfYcQN7g}return false} ) .call(this,rs) ) ||rr.push(r) ;
return rr} ) .call(this,rs) } ,current_list=uniq( (current_list) .concat( ( (function(xs) {var x,x0,xi,xl,xr;
for(var xr=new xs.constructor() ,xi=0,xl=xs.length;
xi<xl;
 ++xi)x=xs[xi] ,xr.push( ( (transitive_limit) .call( {x0:x0,xi:xi,xl:xl,xs:xs,xr:xr} ,x) ) ) ;
return xr} ) .call(this,current_list) ) ) ) ,rewrite=fixed_point;
return(rewrite) } ) .call(this) } } ) ;
