caterwaul.module( 'mulholland.rewrite' ,function($) {$.mulholland.rewriter=function(rules) {;
return(function( ) {var current_list=Array.prototype.slice.call( (rules) ) ,rewrote_something=null,pattern_bloom=function() {;
return(function(xs) {var x,x0,xi,xl,xr;
for(var x0= (0) ,xi=0,xl=xs.length;
xi<xl;
 ++xi)x=xs[xi] ,x0= (x0&x[0] .bloom() ) ;
return x0} ) .call(this,current_list) } ,pattern_complexity=function() {;
return(function(xs) {var x,x0,xi,xl,xr;
for(var x0= (Infinity) ,xi=0,xl=xs.length;
xi<xl;
 ++xi)x=xs[xi] ,x0= (Math.min(x0,x[0] .complexity() ) ) ;
return x0} ) .call(this,current_list) } ,rewrite_once=function(t) {;
return rewrote_something= (function(xs) {var x,x0,xi,xl,xr;
for(var xl=xs.length,xi=xl-1,x=xs[xi] ,x_3_IE1jh7MZlMYml51jyGL6mp;
xi>=0;
 --xi) {x=xs[xi] ;
if(x_3_IE1jh7MZlMYml51jyGL6mp= (x[1] .constructor===Function?x[1] .call(rewrite, (x[0] ) .match(t) ) : (x[1] ) .replace(x[0] .match(t) ) ) )return x_3_IE1jh7MZlMYml51jyGL6mp}return false} ) .call(this,current_list) } ,deep_rewriter=function() {var b=pattern_bloom() ;
var c=pattern_complexity() ;
return function(t) {;
return(b&t.bloom() ) ===b&&t.complexity() >=c? (t) .rmap(rewrite_once) :t} } ,fixed_point=function() {var r=deep_rewriter() ;
var result=function(t) {;
return(rewrote_something=null, (function(it) {return(rewrote_something?fix(it) :it) } ) .call(this, (r(t) ) ) ) } ;
var fix=result;
return result} ,transitive_limit=function(r) {;
return r[1] .constructor===Function?r: [r[0] ,fixed_point() (r[1] ) ] } ,uniq=function(rs) {;
return(function(rs) {var r,r0,ri,rl,rr;
for(var rr=new rs.constructor() ,ri=0,rl=rs.length,r0;
ri<rl;
 ++ri)r=rs[ri] , ( (function(xs) {var x,x0,xi,xl,xr;
for(var x=xs[0] ,xi=0,xl=xs.length,x_3_IE1jh7MZlMYml51jyGL6mp;
xi<xl;
 ++xi) {x=xs[xi] ;
if(x_3_IE1jh7MZlMYml51jyGL6mp= (xi>ri&& (x[0] ) .match(r[0] ) ) )return x_3_IE1jh7MZlMYml51jyGL6mp}return false} ) .call(this,rs) ) ||rr.push(r) ;
return rr} ) .call(this,rs) } ,current_list=uniq( (current_list) .concat( ( (function(xs) {var x,x0,xi,xl,xr;
for(var xr=new xs.constructor() ,xi=0,xl=xs.length;
xi<xl;
 ++xi)x=xs[xi] ,xr.push( ( (transitive_limit) .call( {x0:x0,xi:xi,xl:xl,xs:xs,xr:xr} ,x) ) ) ;
return xr} ) .call(this,current_list) ) ) ) ,rewrite=fixed_point() ;
return(rewrite) } ) .call(this) } } ) ;
